[RTC-192] RTSP component docs
jellyfish-dev/jellyfish-docs pull request #9
Opened 2023-04-17 09:39 UTC by sgfn

2023-04-17 13:55 UTC, mickel8 requested changes
Let's wait with this PR until changes in Jellyfish are merged

2023-04-17 13:55 UTC, mickel8 commented on docs/getting_started/components/rtsp.md
>  Currently, there are no environment variables related to this component.
This needs to be adjusted: we need to either use host network in case of linux or export TCP and UDP ports. See how we do thisi in WebRTC peer

2023-04-17 13:55 UTC, mickel8 commented on docs/getting_started/components/rtsp.md
> +* `rtpPort` (integer 1..65535, default: 20000): Local port RTP stream will be received at
Could we use `-` instead of `:`? I think they are more readable

2023-04-24 09:43 UTC, LVala approved these changes

2023-04-24 15:40 UTC, mickel8 commented on docs/getting_started/components/hls.md
> +you need to create a volume, e.g. by adding the option `-v $(pwd)/output:/app/output`
Unfortunately, this won't work on Linux. On Linux, the created host directory will have `root` owner as docker runs with root privilages. On the other hand, Jellyfish runs as `nobody` and won't be able to write to the `root` directory.

Not sure what we want to do with this. 

In general, there are a couple of solutions:
* use named volumes - but at least in my case, I don't know how to get data out of the named volume
* run docker as root, setup privilages in docker entrypoint and continue running as non-root user using tool like gosu. That's how `redis ` do this
* try to prepare volume directory before running docker - I didn't mange to make it working

2023-04-24 15:42 UTC, mickel8 commented on docs/getting_started/components/hls.md
> +The HLS playlist will be created inside the Docker container. To access it from the host,
Unfortunately, this won't work on Linux. On Linux, the created host directory will have root owner as docker runs with root privilages. On the other hand, Jellyfish runs as nobody and won't be able to write to the root directory.

Not sure what we want to do with this.

In general, there are a couple of solutions:

* use named volumes - but at least in my case, I don't know how to get data out of the named volume
* run docker as root, setup privilages in docker entrypoint and continue running as non-root user using tool like gosu. That's how redis  do this
* try to prepare volume directory before running docker - I didn't mange to make it working

2023-05-09 09:55 UTC, sgfn commented
LGTM!

2023-05-09 13:25 UTC, merged